### ISSUE TITLE
[ISSUE]: ELECT adjustment fail on F-chassis

### ISSUE THREAD

**Issue by AKuHAK** [ps2homebrew/PMAP#4]
### Checks

- [X] I have checked existing issues for duplicates and found none

### Describe the issue

CFD:0x0d0027
CFC:0x020302
After choosing Automatic ELECT adjustment it will pass the CD step. But failed after inserting the DVD. After the lens focuses 4 times (the clicky thing) it completely stops and immediately boots back to the menu with a 2A0 error:

![S6](https://user-images.githubusercontent.com/621640/209943678-4a9fcaee-0cdb-41eb-972c-3383ba494300.PNG)
It's done that on every single F-Chassis I've used on it.

![Eeprom](https://user-images.githubusercontent.com/621640/209943730-b65f2ddc-6dbb-4faf-afbb-24eefb5c5ee8.PNG)

### Console model

SCPH-30003 R

**Comment by AKuHAK** [comment]
Seems it is failing on the executing command:
ce000020000
this returns 2A0 (error code)
ce0 - write to eeprom
0002 - address
0000 - value
need to check this in terminal with some F-chassis

**Comment by AKuHAK** [comment]
fixed in 055351987354c9bd807f6c368e01b66e1cabf044
@sp193 thanks for this incredible tool

**Comment by sp193** [comment]
Thank you for continuing with supporting it, even when I have stopped. And for loving this amazing console.
